#!/bin/bash
BASE=$(dirname $(readlink -f $0))
DATE=$(date +%s)
source $BASE/env

mysqldump -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASSWORD $MYSQLDB > $BACKUPPATH/$DATE.$MYSQLDB.sql
tar czvf $BACKUPPATH/$DATE.documents.tar.gz $DOCUMENTS

COUNT=$(ls -1t $BACKUPPATH/*.sql | wc -l)
echo "Found $COUNT backups"
if [ $COUNT -gt $MAXBACKUP ]; then
	echo "Cleaning old backups"
	TS=$(ls -1t $BACKUPPATH/*.sql | tail -n $[ $COUNT - $MAXBACKUP ] |awk -F\/ '{print $NF}' | awk -F. '{print $1}')
	for T in $TS; do
		rm -f $BACKUPPATH/*$T*
	done
fi 
